
spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/zhaohejing/ghostconfig/
          search-paths: configs
          username: 454258314@qq.com
          password: zwy0410
      label: master
      #kafka
#  stream:
#    kakfa:
#      binder:
#        zk-nodes: 103.45.8.198:2181
#        brokers: 103.45.8.198:9092

server:
  port: 9002
eureka:
  client:
    serviceUrl:
      defaultZone: http://zrc.f3322.net:9001/eureka/
#  profiles: native
#  cloud:
#    config:
#      server:
#        native:
#          search-locations: ../ghost/config/configserver/configs
