
spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/zhaohejing/ghostconfig/
          search-paths: configs
          username: 454258314@qq.com
          password: zwy0410
      label: master
server:
  port: 9000
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/
#  profiles: native
#  cloud:
#    config:
#      server:
#        native:
#          search-locations: ../ghost/config/configserver/configs
