eureka:
  client:
    serviceUrl:
      defaultZone: http://47.94.214.199:9001/eureka/
server:
  port: 9003
spring:
  application:
    name: gateway
zuul:
  routes:
    auth:
      path: /api-auth/**
      serviceId: auth-customer
    order:
      path: /api-order/**
      serviceId: order-customer

hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE
          thread:
            timeout-in-milliseconds: 3000

