eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/
server:
  port: 7000
spring:
  application:
    name: gateway
zuul:
  routes:
    auth:
      path: /auth/**
      serviceId: auth-customer
    order:
      path: /order/**
      serviceId: order-customer

hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE
          thread:
            timeout-in-milliseconds: 3000

