eureka:
  client:
    serviceUrl:
      defaultZone: http://${host:47.94.214.199}:9001/eureka/
server:
  port: 9003
spring:
  application:
    name: gateway
hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE
          thread:
            timeout-in-milliseconds: 3000
