eureka:
  client:
    serviceUrl:
      defaultZone: http://zrc.f3322.net:9001/eureka/
server:
  port: 9005
spring:
  application:
    name: auth-customer

feign:
  hystrix:
    enabled: true

hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE